### PR TITLE
Added a new position sensor based on the FusedLocationProvider of Google...

### PR DESCRIPTION
**Pull request by tedschmidt**
... Play Services
@orhan89 Could you QA and test?

### CODE REVIEW

**Comment by orhan89** [comment]
@tedschmidt: Test this on my phone N7000 and SGS 4, but it seems the GoogleAPI Client never connected. is there something i'm missing here?

**Comment by orhan89** [comment]
@tedschmidt 
after debug the demo application, it seems that we need to call connect on google api client instance explicitly. https://developer.android.com/reference/com/google/android/gms/common/api/GoogleApiClient.html#connect()

i have push a commit to fix this on different branch https://github.com/senseobservationsystems/sense-android-library/tree/feature/play_services_location_explicit_connect . I have test it and the apps seems get the correct location data after. If you think this fix is ok, we might just fast forward this branch to there then.

**Comment by tedschmidt** [comment]
@orhan89 could you check it and if it's ok merge it?

**Comment by orhan89** [comment]
test it, and sending correct data

**Pull request merged**
